<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>89 Click button_Search</name>
   <tag></tag>
   <elementGuidId>b067b10c-5b26-4738-a6cf-7147876a07e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button-style.appearance-filled.size-medium.shape-rectangle.status-basic.nb-transition</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[56]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f899df12-2a76-418d-a1be-3d29fa0abe6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>db26cb73-ab2d-4726-ba8e-1748b42b9bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-style appearance-filled size-medium shape-rectangle status-basic nb-transition</value>
      <webElementGuid>1e8d9d3e-ca46-40a4-8496-09f7a88edfd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8a347b3c-3a16-4479-ad61-e0d2f04c789b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4cc391a4-75b4-4e22-bdc3-b854964605f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>a9be1a38-bc6a-4b58-b28f-97c2108a4ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-34&quot;)/nb-dialog-container[1]/ngx-upload-video-modal[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-md-12&quot;]/nb-card[1]/nb-card-body[1]/div[@class=&quot;d-flex flex-row align-items-center&quot;]/button[@class=&quot;button-style appearance-filled size-medium shape-rectangle status-basic nb-transition&quot;]</value>
      <webElementGuid>b8a1ecac-c8b9-4deb-bbed-6901f082b4f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[56]</value>
      <webElementGuid>f1ce54dc-2d02-4d5d-a8a8-d903fe7f8049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-34']/nb-dialog-container/ngx-upload-video-modal/div/div/nb-card/nb-card-body/div[2]/button</value>
      <webElementGuid>9704bd5b-611e-4437-bea8-bf13e35ffb04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Video'])[1]/following::button[1]</value>
      <webElementGuid>c78498ab-3053-47b4-a3a2-6be2d594cd0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Video'])[2]/preceding::button[1]</value>
      <webElementGuid>95934a37-6948-413f-ad20-df69ca7f0876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[2]</value>
      <webElementGuid>bc495065-cec0-42e1-a1c4-821ce80e39ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>9e584762-3289-4d08-a158-aeb3c4803125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-card-body/div[2]/button</value>
      <webElementGuid>a9b2e401-d2f0-427f-baa0-ce9652be76d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>53e2008f-e58d-42c7-8bd9-8245cdaa1126</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
