<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>11StartDateFilter</name>
   <tag></tag>
   <elementGuidId>2a78f771-9e19-4cb7-a2a0-3086032aa293</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ng-pristine.ng-valid.input-full-width.size-medium.status-basic.shape-rectangle.nb-transition.ng-touched.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>953fae36-60a4-4cc0-8219-df3d5b9c5c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>1287b864-a3f6-42ac-b95d-ba78df310126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>4dd62460-6f66-4fe9-9094-fcf44f7b45b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid input-full-width size-medium status-basic shape-rectangle nb-transition ng-touched cdk-focused cdk-mouse-focused</value>
      <webElementGuid>164b6d2d-e542-4836-a8d0-5190e1d60504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-1&quot;)/nb-dialog-container[1]/ngx-filter-modal[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/nb-card[1]/nb-card-body[1]/div[@class=&quot;d-flex flex-column border-bottom&quot;]/div[@class=&quot;d-flex flex-row justify-content-between align-items-center&quot;]/div[@class=&quot;input-date-style&quot;]/input[@class=&quot;ng-pristine ng-valid input-full-width size-medium status-basic shape-rectangle nb-transition ng-touched cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>06f4a97d-e8d2-4a0e-a143-dcfffa3fcf3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='date']</value>
      <webElementGuid>6d6c9c72-283b-4ee9-9cc4-33fc16a953ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-1']/nb-dialog-container/ngx-filter-modal/div/div/nb-card/nb-card-body/div[2]/div[2]/div/input</value>
      <webElementGuid>0852cf4e-6204-4c4f-92dd-43ab8eb647a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>28c307f9-edf5-4249-bd73-0aaff6239ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'dd/mm/yyyy' and @type = 'date']</value>
      <webElementGuid>6c18d9a3-659b-4416-8278-7307a21312a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
