<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>8ST OB th_Status</name>
   <tag></tag>
   <elementGuidId>0eb2811d-33e2-44ff-bad7-c4e71a487308</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.p-element.p-sortable-column.p-resizable-column.ng-star-inserted.p-highlight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='pr_id_12-table']/thead/tr/th[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>74fdac81-1654-4b78-b121-80ccc3568d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element p-sortable-column p-resizable-column ng-star-inserted p-highlight</value>
      <webElementGuid>bac37eaa-d625-4ea0-885a-4fb6fb528c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-field</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>f2a3ae7d-c474-4ba9-927b-a3cdcce22c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1d7d3b9c-0cb5-4dfb-af67-1e22d96f7a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>columnheader</value>
      <webElementGuid>0b8eb5b6-de8e-4497-85c0-a4c7eef448e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-sort</name>
      <type>Main</type>
      <value>descending</value>
      <webElementGuid>c6d361a9-d00c-46a8-b63e-75d36c2bc5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Status </value>
      <webElementGuid>a0c4193c-2b83-46d0-85b9-afddd826e4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_12-table&quot;)/thead[@class=&quot;p-datatable-thead&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/th[@class=&quot;p-element p-sortable-column p-resizable-column ng-star-inserted p-highlight&quot;]</value>
      <webElementGuid>e90d5884-dc71-4155-a873-4acd9028acd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pr_id_12-table']/thead/tr/th[5]</value>
      <webElementGuid>3423e102-5aae-47b1-a15f-83817384ded5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaign Terhubung'])[2]/following::th[1]</value>
      <webElementGuid>1cd50978-7d27-4d85-abca-915cac317c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balance'])[2]/following::th[2]</value>
      <webElementGuid>00140b06-a25b-4f6d-8071-3a43d9665bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet Point MSR'])[1]/preceding::th[2]</value>
      <webElementGuid>e19c367f-5759-4900-9ebb-2998255be338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POINT'])[3]/preceding::th[2]</value>
      <webElementGuid>7a6a9882-3144-4e92-83b2-117084e90312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-tabpanel[2]/div/div[2]/div/p-table/div/div/table/thead/tr/th[5]</value>
      <webElementGuid>be5742c7-c806-48a5-810a-64e59b6b78d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = ' Status ' or . = ' Status ')]</value>
      <webElementGuid>98d73bb6-1a7e-4b9a-8e97-9d133df8b950</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
