<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_User Tags MD</name>
   <tag></tag>
   <elementGuidId>87f0b7b2-45cc-4d9c-801e-ba6706157a42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p-tabpanel-0']/user-group/nb-tabset/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ad9fa0a8-cc42-4151-b7a2-747cc4f843c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4937fd2c-4657-4755-b576-09bd7947935b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-link</value>
      <webElementGuid>1c25a4e1-9ec3-4833-a8d2-896038cf8ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User Tags MD</value>
      <webElementGuid>b2ee1d26-576d-4ec7-8e62-0d15580a4962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/user-group[1]/nb-tabset[1]/ul[@class=&quot;tabset&quot;]/li[@class=&quot;tab ng-star-inserted&quot;]/a[@class=&quot;tab-link&quot;]</value>
      <webElementGuid>b413422b-928d-40c4-9fb1-63ebde5c9eb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-0']/user-group/nb-tabset/ul/li[2]/a</value>
      <webElementGuid>1f55a7c9-767e-4fc8-8cc4-bae39133213c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Tags'])[1]/following::a[1]</value>
      <webElementGuid>c803f2a3-9f3c-4bc4-8fa6-207cca420d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pemenang Group'])[1]/following::a[2]</value>
      <webElementGuid>8311103d-b14d-40f6-af27-331c7d7097a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse User'])[1]/preceding::a[1]</value>
      <webElementGuid>749f2d2a-2efc-4fb6-b431-e0765c0599c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[42]</value>
      <webElementGuid>b844284d-bdd4-47a9-a6d5-886f3d679f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-tabset/ul/li[2]/a</value>
      <webElementGuid>c02dbfad-125c-4a20-91a3-095d3c1aaa7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'User Tags MD' or . = 'User Tags MD')]</value>
      <webElementGuid>3e44bb39-c630-48a6-88fc-558c37cea39a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
