<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>3.1 Pilihan IAK</name>
   <tag></tag>
   <elementGuidId>6334a049-8407-43fa-86d1-8c4deac64039</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nb-option[@id='nb-option-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nb-option-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nb-option</value>
      <webElementGuid>119b98e5-1d72-4f5a-b87d-1ecbb23b352b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>IAK</value>
      <webElementGuid>c9ac0d7a-7fb4-4f65-8868-0691fc854eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3d03ebff-9c78-46d4-8888-d5557e43ba2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nb-option-1</value>
      <webElementGuid>77b09870-efd4-4fee-ad89-c56d8fd4ddfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nb-transition ng-star-inserted</value>
      <webElementGuid>e9ba5fda-a8ee-42b9-ad25-548e02a0df8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> IAK </value>
      <webElementGuid>98b7ace4-decf-4096-8142-215dd44b0aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nb-option-1&quot;)</value>
      <webElementGuid>e9b90a56-ead0-433d-bb62-5af90383fe2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//nb-option[@id='nb-option-1']</value>
      <webElementGuid>9821bd3f-9e80-4935-a069-d5ae5b984876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-2']/nb-option-list/ul/nb-option</value>
      <webElementGuid>a48dec8c-e5ca-47b7-b5a7-dc5faf412eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::nb-option[1]</value>
      <webElementGuid>eb6d56f5-2e4b-48c3-8eb5-7e29b3e21fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[2]/following::nb-option[1]</value>
      <webElementGuid>1edccca8-63fc-40bb-8802-4e38532f423f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BKT'])[6]/preceding::nb-option[1]</value>
      <webElementGuid>b80fcef8-bfbf-4352-8785-f78c7fd73f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::nb-option[2]</value>
      <webElementGuid>0c321928-36ad-40fa-ac8d-276670b2debf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-option</value>
      <webElementGuid>4f878949-88c3-4d45-88a0-86d9a7ae20b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nb-option[@id = 'nb-option-1' and (text() = ' IAK ' or . = ' IAK ')]</value>
      <webElementGuid>8801c77c-c5bf-451a-9c1e-b9a6c958fa6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
