<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Keterangan_ng-untouched input-full_c08075</name>
   <tag></tag>
   <elementGuidId>b6b2ad9d-6b28-45a0-ab27-8c780953c9ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.ng-untouched.input-full-width.size-medium.status-primary.shape-rectangle.nb-transition.cdk-focused.cdk-mouse-focused.ng-dirty.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-0']/nb-dialog-container/form-provinsi-group/div/div/nb-card/nb-card-body/form/div[2]/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d2ba3c46-ac45-49fb-a000-aaf5f67d030c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>e3cc9986-153a-4a4b-978e-a4c9879c7564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>keterangan</value>
      <webElementGuid>25bf2132-1acd-4560-9b7e-f1d5c315e349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Keterangan</value>
      <webElementGuid>883a43ee-2f12-4a21-8481-f4219731fcb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>cdaf10a2-df2a-493c-83af-59a8f29af2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>keterangan</value>
      <webElementGuid>78c1b2cf-cacc-4d21-8153-7b3380526204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>d07bf5b2-ec77-4ce4-81e4-b2f97e8b5f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched input-full-width size-medium status-primary shape-rectangle nb-transition cdk-focused cdk-mouse-focused ng-dirty ng-valid</value>
      <webElementGuid>775e26df-dae8-41c9-8c0c-9982e6d8e4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-0&quot;)/nb-dialog-container[1]/form-provinsi-group[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/nb-card[1]/nb-card-body[1]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;row py-2&quot;]/div[@class=&quot;col-md-12&quot;]/textarea[@class=&quot;ng-untouched input-full-width size-medium status-primary shape-rectangle nb-transition cdk-focused cdk-mouse-focused ng-dirty ng-valid&quot;]</value>
      <webElementGuid>59bbe277-2793-4245-9511-a17993fe48d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-0']/nb-dialog-container/form-provinsi-group/div/div/nb-card/nb-card-body/form/div[2]/div/textarea</value>
      <webElementGuid>de34eefa-d42b-40d7-97e5-2da39ad7bc5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>66db4af8-ffa6-4bc0-aaa8-c693a7fd6dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Masukkan Keterangan']</value>
      <webElementGuid>3d2cba6d-f887-4fbf-9be9-f66667e52c26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
