<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>9Click nb-option_Berlaku Kelipatan</name>
   <tag></tag>
   <elementGuidId>a164405f-0a8d-40b7-9617-844c05c9113d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nb-option-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim'])[1]/following::nb-option[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nb-option</value>
      <webElementGuid>ba08c30d-8c65-4b23-be72-f2931d0a2162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>fb3e9dc0-ce6c-4cc3-848b-073d1b259e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>55bdc75c-f749-445b-af74-e29642d53eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>19c3a823-cb6e-44ef-860e-0e117498f3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nb-option-6</value>
      <webElementGuid>fa498bbe-4840-4fe1-ac54-dbd107b8467b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nb-transition</value>
      <webElementGuid>088da239-95cf-4060-8490-da39c3c18681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Berlaku Kelipatan</value>
      <webElementGuid>abc263d6-0ad1-4ad6-8534-45171c373513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nb-option-6&quot;)</value>
      <webElementGuid>fd0b51a6-cb4b-477a-9a67-4a951c89cdc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//nb-option[@id='nb-option-6']</value>
      <webElementGuid>3812a9f9-8268-4688-a86e-3705b0030fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-4']/nb-option-list/ul/nb-option</value>
      <webElementGuid>341ed115-73f6-4dc5-ade9-1f53964ff91b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim'])[1]/following::nb-option[1]</value>
      <webElementGuid>5378a765-b84c-4442-a603-dc3923528517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak Berlaku Kelipatan'])[1]/preceding::nb-option[1]</value>
      <webElementGuid>2278c303-e62e-4e54-adee-539e7527461b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::nb-option[2]</value>
      <webElementGuid>8865279e-c9ff-424b-a63c-a132cb84f5f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Berlaku Kelipatan']/parent::*</value>
      <webElementGuid>36962e61-404d-4bdf-b5bf-7d9528cb2a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-option</value>
      <webElementGuid>e13f76d8-9ab3-4069-916d-a4ce9cb11b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nb-option[@id = 'nb-option-6' and (text() = 'Berlaku Kelipatan' or . = 'Berlaku Kelipatan')]</value>
      <webElementGuid>3dde7ce1-fd02-4896-830b-4257f1eff1d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
