<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>23 ST Maximum Redeem Per User</name>
   <tag></tag>
   <elementGuidId>248cd3e4-4bcb-4c17-8a92-04a2d0e6c8c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.mt-2.ng-untouched.ng-pristine.ng-invalid.input-full-width.size-medium.status-primary.shape-rectangle.nb-transition.cdk-focused.cdk-mouse-focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='number'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b1e893c-0f8e-4b7a-9830-421d117cb824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>1de20abc-96de-41a0-887a-6103cf0054e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>max_redeem_per_user</value>
      <webElementGuid>e13e333f-968f-40a1-b907-78947d933399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a04c956d-cca1-4439-80a0-1ec588e2651a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d7b404c2-9603-46be-8ca9-c1c8b25e88e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Jumlah Stok</value>
      <webElementGuid>f67e9515-c611-420e-96b2-e7eae405bf83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value &lt; 0 ? this.value = 1 : this.value</value>
      <webElementGuid>c930d79b-8eb3-476b-b2b6-17d27c95fcea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-2 ng-untouched ng-pristine ng-invalid input-full-width size-medium status-primary shape-rectangle nb-transition cdk-focused cdk-mouse-focused</value>
      <webElementGuid>11a5ecc4-4e2c-4ab3-932b-634005eed7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>785f9dc2-2cfd-4f48-b30e-27ca3146bf81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>max_redeem_per_user</value>
      <webElementGuid>fa9c32fc-f32a-4f42-8e29-29ce1d80265e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>7f776911-4688-4502-ae3d-b29b99fd5bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-5&quot;)/nb-dialog-container[1]/form-reward-regular[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/nb-card[1]/nb-card-body[1]/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;row p-3&quot;]/div[@class=&quot;col-md-12&quot;]/input[@class=&quot;mt-2 ng-untouched ng-pristine ng-invalid input-full-width size-medium status-primary shape-rectangle nb-transition cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>5b639163-4fb2-426b-89a9-f56793506e7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='number'])[2]</value>
      <webElementGuid>06318207-74c1-4898-a0ec-ebab35e79c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-5']/nb-dialog-container/form-reward-regular/div/div/nb-card/nb-card-body/form/div[3]/div/input</value>
      <webElementGuid>b30b0bab-4a78-4e80-b00c-e26713353763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>916e059a-60cc-47cd-a025-89d6fae5064a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Masukkan Jumlah Stok']</value>
      <webElementGuid>13da5092-8af7-4163-8f51-4bb44eb5bf45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
