<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>27 Click button_--Pilih Tipe Wallet--</name>
   <tag></tag>
   <elementGuidId>84ebcad2-3500-4b74-95e3-3cc5fbda1f81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nb-select.mt-2.appearance-outline.full-width.size-medium.status-primary.shape-rectangle.ng-pristine.ng-invalid.nb-transition.ng-touched > button.select-button.placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[20]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>da7d3fc2-8432-4de3-b5e9-d58f7f585511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a77f057a-0a80-445c-9b03-9c9394f77f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-button placeholder</value>
      <webElementGuid>80e73ced-1d19-4a7c-bbf3-87f22a468e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>placeholder</value>
      <webElementGuid>b2a0df34-d4ea-41e2-828c-61639bcd62dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Pilih Tipe Wallet--</value>
      <webElementGuid>f7edd627-b31b-4896-9749-154082f0c647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-5&quot;)/nb-dialog-container[1]/form-reward-regular[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/nb-card[1]/nb-card-body[1]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;row price-section-border ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;col-md-12 ng-star-inserted&quot;]/div[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/nb-select[@class=&quot;mt-2 appearance-outline full-width size-medium status-primary shape-rectangle ng-pristine ng-invalid nb-transition ng-touched&quot;]/button[@class=&quot;select-button placeholder&quot;]</value>
      <webElementGuid>fb5e8680-f6b8-4c05-82a7-1cd9a6cbc528</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[20]</value>
      <webElementGuid>4ee00f54-e488-48d9-a6ba-d4d195b5e40d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-5']/nb-dialog-container/form-reward-regular/div/div/nb-card/nb-card-body/form/div[5]/div/div/div/div[4]/nb-select/button</value>
      <webElementGuid>3b6b9c2e-6bd6-4416-bb4a-4cded0f9824e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga'])[1]/following::button[1]</value>
      <webElementGuid>19a4d5bd-9256-45cf-8494-23e64e5bf52f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WIB'])[4]/following::button[1]</value>
      <webElementGuid>37f9fd9f-f380-4a7f-90b4-3bff8b0fe1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set Harga Diskon (Opsional)'])[1]/preceding::button[1]</value>
      <webElementGuid>93358280-44f0-40d7-a2aa-41e5fe435953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/nb-select/button</value>
      <webElementGuid>1741b476-5db4-4a9f-89c0-19150efde500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '--Pilih Tipe Wallet--' or . = '--Pilih Tipe Wallet--')]</value>
      <webElementGuid>0fb27e50-595d-4c77-9bdf-369e51c4fcf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
