<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>1. Banner Campaign Upload JPG PNG</name>
   <tag></tag>
   <elementGuidId>7af233eb-835b-4ff1-9bb7-99c9fc9570c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mb-3.appearance-filled.size-medium.shape-round.status-primary.nb-transition</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ngx-one-column-layout[@id='body']/nb-layout/div/div/div/div/div/nb-layout-column/ngx-editors/campaign-templates/nb-card/nb-card-body/program-qrcode/nb-tabset/nb-tab/setting-a-qrcode/form/div/div[14]/div/p/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b0f613c-450f-4446-b32e-7835a74fa3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>8fcc6f79-5dec-448c-aa7b-c4aef5514a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>0d468565-ab7d-48ac-8d4d-f6a3609cd035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-3 appearance-filled size-medium shape-round status-primary nb-transition</value>
      <webElementGuid>7ff522fc-2cb8-4212-aba3-e11a03b1df22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-shape</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>a9ce24a7-e996-4c92-9575-707ef6d5dd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>30426c5f-ba55-4230-af85-2be5775d4116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>206b7d1a-9a29-4949-a215-ec1060d68c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ebb7ee25-6bf1-4309-ad48-3a024c210399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Select File </value>
      <webElementGuid>5abb1bb7-82ed-4dd7-8e60-13e1c8fb43a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/nb-layout[@class=&quot;window-mode with-scroll&quot;]/div[@class=&quot;scrollable-container&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;layout-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;columns&quot;]/nb-layout-column[1]/ngx-editors[@class=&quot;ng-star-inserted&quot;]/campaign-templates[@class=&quot;ng-star-inserted&quot;]/nb-card[1]/nb-card-body[@class=&quot;ng-star-inserted&quot;]/program-qrcode[@class=&quot;ng-star-inserted&quot;]/nb-tabset[1]/nb-tab[@class=&quot;content-active&quot;]/setting-a-qrcode[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-9 mb-4&quot;]/div[@class=&quot;image vertical-center ng-star-inserted&quot;]/p[1]/button[@class=&quot;mb-3 appearance-filled size-medium shape-round status-primary nb-transition&quot;]</value>
      <webElementGuid>ec8ff00c-c917-4a10-8d77-221deeca7b96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ngx-one-column-layout[@id='body']/nb-layout/div/div/div/div/div/nb-layout-column/ngx-editors/campaign-templates/nb-card/nb-card-body/program-qrcode/nb-tabset/nb-tab/setting-a-qrcode/form/div/div[14]/div/p/button</value>
      <webElementGuid>c14578b3-c90b-4147-a9ec-fe0fed88fbf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or'])[1]/following::button[1]</value>
      <webElementGuid>855bdb52-1b5c-4230-b9ac-7bebbafa5140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banner akan ditampilkan di card campaign di sebelah kanan atas.'])[1]/following::button[1]</value>
      <webElementGuid>6cb5df9b-0aba-4eed-8881-2db8de2ac502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size: 320pxl * 320pxl'])[1]/preceding::button[1]</value>
      <webElementGuid>2b600b50-aca8-4019-8214-e14d65928af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/button</value>
      <webElementGuid>f6b06760-6d13-4504-bf9c-41f14fcf1257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Select File ' or . = ' Select File ')]</value>
      <webElementGuid>0d4f1b9f-f956-4c83-afa7-f7f598ea6a24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
