<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_provinsi-msr-1</name>
   <tag></tag>
   <elementGuidId>c85116af-5da2-4d26-ab27-40e8d3efc33b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nb-option-30 > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nb-option[@id='nb-option-30']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d2a4c86e-e662-43f1-9523-16d47d85e11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>provinsi-msr-1</value>
      <webElementGuid>eeef3692-d110-49f4-96cf-95844e672164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nb-option-30&quot;)/div[1]</value>
      <webElementGuid>6606b189-1916-44bc-9683-97913edcd81b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nb-option[@id='nb-option-30']/div</value>
      <webElementGuid>83235af5-145d-4509-b501-dd4d04d7a550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kabupaten-msr-1'])[2]/following::div[1]</value>
      <webElementGuid>82e30418-acb5-4b95-bbe9-a0de567bf65b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZKABUPATEN1'])[1]/following::div[2]</value>
      <webElementGuid>f74d1029-fc54-4a26-bb72-0969fe211c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='provinsi-msr-2'])[1]/preceding::div[1]</value>
      <webElementGuid>a0da5593-1e7e-4b2b-a120-2afa2e0e6310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='senen'])[1]/preceding::div[2]</value>
      <webElementGuid>2796d3f1-fd19-4c56-a2d8-2d2efbe4c794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='provinsi-msr-1']/parent::*</value>
      <webElementGuid>e29d8843-44c9-4bb3-9724-f5b14829e03c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-option[12]/div</value>
      <webElementGuid>50a776b7-7b80-483c-93aa-cc5222b0809b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'provinsi-msr-1' or . = 'provinsi-msr-1')]</value>
      <webElementGuid>7c08ea5b-5aba-4e03-8b25-e3824159f1e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
