<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nb-option_Karyawan</name>
   <tag></tag>
   <elementGuidId>3ffe30ae-1e12-4941-aef5-effdc6d54cd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nb-option-16</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nb-option[@id='nb-option-16']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nb-option</value>
      <webElementGuid>eb7d6268-ce03-4aa7-9505-d6c9696a4f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>karyawan</value>
      <webElementGuid>b76ae764-f1ae-46ed-b6ce-a45a593e4e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f5c0574b-6909-4ab5-80e8-20d8c105ae53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nb-option-16</value>
      <webElementGuid>e2f75863-0d3b-4824-9711-8555eb18d68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiple nb-transition ng-star-inserted</value>
      <webElementGuid>2a075565-3512-4705-91c5-59656ccca480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Karyawan</value>
      <webElementGuid>d2c75fbb-8f95-491d-abad-9ecf337e881e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nb-option-16&quot;)</value>
      <webElementGuid>a9847533-7ddd-4cab-9159-bb3e44a1d61a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//nb-option[@id='nb-option-16']</value>
      <webElementGuid>37fe4d05-7b92-472c-8cb8-7c8ad1351594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-5']/nb-option-list/ul/nb-option</value>
      <webElementGuid>326dc5a1-7e88-4576-bb52-8179d1ee657a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim'])[1]/following::nb-option[1]</value>
      <webElementGuid>1b3ed43e-6f4d-4326-a716-5a78f2714434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'nb-option-16', '&quot;', ')')])[1]/preceding::nb-option[1]</value>
      <webElementGuid>31ea3665-3eb3-4385-9f83-1f314e01725d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Karyawan']/parent::*</value>
      <webElementGuid>85e97e0f-6621-4448-be1c-2546f72ea901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-option</value>
      <webElementGuid>bbe507c5-5015-4e11-b712-191cdeebb1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nb-option[@id = 'nb-option-16' and (text() = 'Karyawan' or . = 'Karyawan')]</value>
      <webElementGuid>635a8efb-65ee-41a9-b41c-f8de98f055aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
