<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>10Click img</name>
   <tag></tag>
   <elementGuidId>e9abd777-c3c7-4042-a1c6-ad12f95113ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='pr_id_1-table']/tbody/tr[3]/td[8]/div/a/nb-icon/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1200c307-8021-4235-b19e-e02ff3bc11ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/icons/compare.svg</value>
      <webElementGuid>89dcb186-0871-4b94-a6a9-e04c5761e2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_1-table&quot;)/tbody[@class=&quot;p-element p-datatable-tbody&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/td[8]/div[@class=&quot;ng-star-inserted&quot;]/a[1]/nb-icon[1]/img[1]</value>
      <webElementGuid>aa722476-0b93-48cc-90f5-5af6a9393a13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pr_id_1-table']/tbody/tr[3]/td[8]/div/a/nb-icon/img</value>
      <webElementGuid>6a08566e-3c39-4408-af83-75d92aac7780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[8]/div/a/nb-icon/img</value>
      <webElementGuid>2b6e0352-cb70-4765-97da-44834050c48b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/icons/compare.svg']</value>
      <webElementGuid>89c5d5f8-6a2a-4af6-bd63-9cf8481e8af3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
