<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>98 Click nb-option_Program Campaign Quiz</name>
   <tag></tag>
   <elementGuidId>20f7263b-213c-489a-b1a7-e595612b6838</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nb-option[@id='nb-option-239']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nb-option-239</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nb-option</value>
      <webElementGuid>62c943a5-1196-4a20-b478-387492cc9a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>QUIZ</value>
      <webElementGuid>6d218ac0-a9b2-4a68-9975-8bdb2c81a3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>QUIZ</value>
      <webElementGuid>6eee80a7-36e8-4919-84ad-a5393ca342fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9031ccc5-c1ab-4426-9310-6bccc968bcc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nb-option-239</value>
      <webElementGuid>59d51cc7-6116-4142-a7c4-1c1338975777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nb-transition</value>
      <webElementGuid>537f1ed9-0eb7-48d1-90db-2de4ea0f5673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Program Campaign Quiz</value>
      <webElementGuid>96cc9d28-0f15-4899-930e-7ffc0c7aa516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nb-option-239&quot;)</value>
      <webElementGuid>6fd1d5e3-3481-4852-a0c5-f2dd5e7b52c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//nb-option[@id='nb-option-239']</value>
      <webElementGuid>24fa8ca5-fe6a-4ac5-9745-56c705177c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-1']/nb-option-list/ul/nb-option[3]</value>
      <webElementGuid>4ae0d91a-8dfc-40aa-acb3-62216fbc7b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program Campaign Foto'])[1]/following::nb-option[1]</value>
      <webElementGuid>e75000c1-67a8-4fbf-9bd9-ede175bb1d90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program Scan QR Code'])[1]/following::nb-option[2]</value>
      <webElementGuid>8d205f2d-0b09-4bde-9f4d-b8db593981ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::nb-option[1]</value>
      <webElementGuid>c847a7ee-f527-4ca6-b96b-dc9130116afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::nb-option[1]</value>
      <webElementGuid>32229623-d8c5-45c4-9d32-2972da151517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Program Campaign Quiz']/parent::*</value>
      <webElementGuid>6629b4d6-cce0-4572-b0b4-8e447a749d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-option[3]</value>
      <webElementGuid>26ef3013-2ad7-4b15-9baf-2ff8ca2df257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nb-option[@id = 'nb-option-239' and (text() = 'Program Campaign Quiz' or . = 'Program Campaign Quiz')]</value>
      <webElementGuid>7e2e576f-0c7c-40b1-a545-6739f39b38d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
