<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>18.1 Click nb-option_A-PEMENANG-PERINGKAT</name>
   <tag></tag>
   <elementGuidId>98635317-00b3-4945-a331-bd01541c967e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim'])[1]/following::nb-option[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nb-option-20</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nb-option</value>
      <webElementGuid>5adc3175-ba4d-498c-acd8-9b97c4161ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>A-PEMENANG-PERINGKAT</value>
      <webElementGuid>dcac0d85-9efd-4da1-992d-a448ea795788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6832d748-48b5-4ca8-b758-27f0450c503e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nb-option-20</value>
      <webElementGuid>a8371538-4d61-4daf-81af-3a4727d1f3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiple nb-transition ng-star-inserted</value>
      <webElementGuid>991e83af-89e9-4cd9-b532-b1f842c68dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A-PEMENANG-PERINGKAT</value>
      <webElementGuid>7c3cba01-379f-4a20-ad62-706bffd1f035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nb-option-20&quot;)</value>
      <webElementGuid>87c01bd6-ec52-453c-b8de-110e1890cc5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//nb-option[@id='nb-option-20']</value>
      <webElementGuid>d3de4865-1878-4abc-b1e8-2a3ea2ab8035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-4']/nb-option-list/ul/nb-option</value>
      <webElementGuid>9a29ccbe-e8e3-4199-bafe-8888b9f8a59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim'])[1]/following::nb-option[1]</value>
      <webElementGuid>b07bac0b-2741-456e-95b6-48a097de7a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GROUP TOKO CURANG'])[1]/preceding::nb-option[1]</value>
      <webElementGuid>4f43e74f-aaee-4e69-bb8f-a7b6e20631d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-option</value>
      <webElementGuid>6d987806-7567-435e-aaa6-f04cb2cae359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nb-option[@id = 'nb-option-20' and (text() = 'A-PEMENANG-PERINGKAT' or . = 'A-PEMENANG-PERINGKAT')]</value>
      <webElementGuid>1ccad627-a6e7-43f7-800f-19a267fd4d1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
