<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>18.1 Click nb-option_NEWGROUPTC</name>
   <tag></tag>
   <elementGuidId>ed0f00a6-6afe-494d-9ebb-ae8a12cc5f8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nb-option-22</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='GROUP TOKO CURANG'])[1]/following::nb-option[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nb-option</value>
      <webElementGuid>ef51abe7-d55c-471d-82dd-fea414936a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>NEWGROUPTC</value>
      <webElementGuid>cc8b0311-c917-4367-8c74-36ad40c34374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>017fb28d-dfa9-48ad-8266-fbc2b67ca660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nb-option-22</value>
      <webElementGuid>78048cba-a11f-4863-8a66-1b0b0c57d688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiple nb-transition ng-star-inserted</value>
      <webElementGuid>c73e1220-64d6-4e0b-b6b3-67702727c406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEWGROUPTC</value>
      <webElementGuid>24ca0359-d4be-48e4-898e-14a98d53cdc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nb-option-22&quot;)</value>
      <webElementGuid>a215f2ba-73aa-4259-910b-3358e8198483</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//nb-option[@id='nb-option-22']</value>
      <webElementGuid>d9cf0d90-9dc2-4509-b198-d6647c189ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-4']/nb-option-list/ul/nb-option[3]</value>
      <webElementGuid>c1c968d4-f45c-4b50-acad-99fef75f1fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GROUP TOKO CURANG'])[1]/following::nb-option[1]</value>
      <webElementGuid>802b78c6-2db0-492b-8a45-ec7d1a394467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-PEMENANG-PERINGKAT'])[1]/following::nb-option[2]</value>
      <webElementGuid>02269370-280f-4e63-abed-0637e0ce4c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROVINSI-MSR-3'])[1]/preceding::nb-option[1]</value>
      <webElementGuid>079c2b29-aae4-40d2-9dbc-daca83372182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-option[3]</value>
      <webElementGuid>b2d627a7-6de6-4e8d-9f15-eedb1ee76681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nb-option[@id = 'nb-option-22' and (text() = 'NEWGROUPTC' or . = 'NEWGROUPTC')]</value>
      <webElementGuid>449bc0dd-1507-41f5-9e0b-11190d4e569a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
