<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nb-option_TCNew</name>
   <tag></tag>
   <elementGuidId>db8c9708-3c7b-466e-b643-2033299fe030</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nb-option[@id='nb-option-8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nb-option-8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nb-option</value>
      <webElementGuid>323fc146-16f0-44b2-8919-12d23866feae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>tcnew</value>
      <webElementGuid>aa41c2b7-4bd9-4e26-a4a4-dfd262a57d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>649c7778-8cd4-4850-84d7-c35634bed585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nb-option-8</value>
      <webElementGuid>3f16a7be-738f-48f8-923e-c2da82a619f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nb-transition ng-star-inserted</value>
      <webElementGuid>7c18b079-1623-4958-9414-15bee70a674d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TCNew</value>
      <webElementGuid>b2e74495-827c-444c-9919-8bc50af90bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nb-option-8&quot;)</value>
      <webElementGuid>0e23e7c8-a203-45f3-9fdb-c65520d86e5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//nb-option[@id='nb-option-8']</value>
      <webElementGuid>760f5076-bcf9-4565-8728-f1132f386049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-0']/nb-option-list/ul/nb-option</value>
      <webElementGuid>73431ef6-9b98-46d3-af74-6990896161a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Data!'])[1]/following::nb-option[1]</value>
      <webElementGuid>2cee0071-ef47-4a07-af4e-8681161cf872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet Point MSR 2'])[1]/preceding::nb-option[1]</value>
      <webElementGuid>be826aed-966a-4a26-b269-18eb263703af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet Rupiah MSR'])[1]/preceding::nb-option[2]</value>
      <webElementGuid>b9ada938-e16a-4a99-af0f-031e0a36bb1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TCNew']/parent::*</value>
      <webElementGuid>50e1311b-9236-45d0-b6aa-2344d79caa34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-option</value>
      <webElementGuid>b9f0bad3-3fe6-434b-b39e-bbd98ab6dbb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nb-option[@id = 'nb-option-8' and (text() = 'TCNew' or . = 'TCNew')]</value>
      <webElementGuid>3ce7d4e5-14b9-4880-bee8-fd35fb77b8ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
