<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>10 Click button_Add Question 2</name>
   <tag></tag>
   <elementGuidId>32608fae-055f-461d-8613-9e9c4823f508</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nb-tab.tab-periode-style.ng-star-inserted.content-active > div.d-flex.p-1.flex-row.ng-star-inserted > div.col-4.p-0.side-card > div.d-flex.flex-column > button.m-2.mb-3.button-add.appearance-filled.size-medium.shape-round.icon-start.status-primary.nb-transition</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[20]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d4146db4-2a68-47e7-b15c-e8229e7cdadd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c7bbeb8-fed3-4875-972d-2a0cdebb74e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>aa0c601f-1ec0-4ca3-94ee-b14f63a79da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>434703b4-37fe-4f4c-b460-4aa8841d4ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nbspinnerstatus</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>f27e18ed-f49b-4b50-a338-c6f8ef0ae374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-2 mb-3 button-add appearance-filled size-medium shape-round icon-start status-primary nb-transition</value>
      <webElementGuid>c6949f8d-6d01-41f1-92ff-4abafb8eae26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-shape</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>d7d5beea-e6c5-439d-8824-3c03d96bf05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>8d1e9303-c11f-4fd6-b4d8-721d4dbdef6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-spinner-status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>f64a5344-bb61-4116-91f9-face266dc297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d98ecf62-55fd-48a6-847d-809238334cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b9a47a2e-5f20-40c0-9364-2bbe54186b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add Question </value>
      <webElementGuid>6af8239a-dcb0-40ac-bc43-b239aa18fc9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/nb-layout[@class=&quot;window-mode with-scroll&quot;]/div[@class=&quot;scrollable-container&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;layout-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;columns&quot;]/nb-layout-column[1]/ngx-editors[@class=&quot;ng-star-inserted&quot;]/campaign-templates[@class=&quot;ng-star-inserted&quot;]/nb-card[1]/nb-card-body[@class=&quot;ng-star-inserted&quot;]/program-quiz[@class=&quot;ng-star-inserted&quot;]/nb-tabset[1]/nb-tab[@class=&quot;p-0 content-active&quot;]/setting-d-quiz[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/nb-tabset[1]/nb-tab[@class=&quot;tab-periode-style ng-star-inserted content-active&quot;]/div[@class=&quot;d-flex p-1 flex-row ng-star-inserted&quot;]/div[@class=&quot;col-4 p-0 side-card&quot;]/div[@class=&quot;d-flex flex-column&quot;]/button[@class=&quot;m-2 mb-3 button-add appearance-filled size-medium shape-round icon-start status-primary nb-transition&quot;]</value>
      <webElementGuid>9213bd58-a29b-4605-b414-7debad672c22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[20]</value>
      <webElementGuid>c92e094c-44de-4566-a3ba-6e61bd550efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ngx-one-column-layout[@id='body']/nb-layout/div/div/div/div/div/nb-layout-column/ngx-editors/campaign-templates/nb-card/nb-card-body/program-quiz/nb-tabset/nb-tab[3]/setting-d-quiz/form/nb-tabset/nb-tab[3]/div/div/div/button</value>
      <webElementGuid>1b778166-fc20-493d-80d1-acbc21dc4de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Match'])[3]/following::button[1]</value>
      <webElementGuid>a6dd9c04-b079-4606-aec1-8285ce7e6247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Match'])[2]/following::button[1]</value>
      <webElementGuid>0393f099-d017-486f-aec1-ab3ac55efdf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Optional)'])[3]/preceding::button[1]</value>
      <webElementGuid>f4f407f5-c542-4ad6-a569-914311028837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-tab[3]/div/div/div/button</value>
      <webElementGuid>29f92d32-3c57-4ddd-a3c7-d603e0c55925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Add Question ' or . = ' Add Question ')]</value>
      <webElementGuid>93ad7664-f1ec-4708-a886-85d76abaa7af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
