<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>14.1 Write</name>
   <tag></tag>
   <elementGuidId>c0c7334f-ee4e-4189-9d38-11fb4c3819ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.flex-column.ng-tns-c181-57 > div.d-flex.flex-row.mt-2 > p-checkbox[name=&quot;filter-cabang&quot;] > div.p-checkbox.p-component > div.p-checkbox-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p-tabpanel-0']/ngx-roles-menus/nb-accordion/nb-accordion-item[10]/nb-accordion-item-body/div/div/div/div[2]/p-checkbox/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>53887f7d-1fac-4e85-9c2c-c28b135caae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-checkbox-box</value>
      <webElementGuid>35b751a8-596a-47de-82c4-8b5ede93c775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>fe4de0bb-ed9a-41f3-9a00-8ed94be465a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/ngx-roles-menus[1]/nb-accordion[@class=&quot;box-noshadow&quot;]/nb-accordion-item[@class=&quot;ng-star-inserted expanded&quot;]/nb-accordion-item-body[@class=&quot;ng-tns-c181-57 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c181-57 ng-trigger ng-trigger-accordionItemBody&quot;]/div[@class=&quot;item-body ng-tns-c181-57&quot;]/div[@class=&quot;d-flex flex-column ng-tns-c181-57&quot;]/div[@class=&quot;d-flex flex-row mt-2&quot;]/p-checkbox[@class=&quot;p-element mr-2 ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;p-checkbox p-component&quot;]/div[@class=&quot;p-checkbox-box&quot;]</value>
      <webElementGuid>22b8fb86-9e44-4262-b2fb-d06f690cca16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-0']/ngx-roles-menus/nb-accordion/nb-accordion-item[10]/nb-accordion-item-body/div/div/div/div[2]/p-checkbox/div/div[2]</value>
      <webElementGuid>de98da10-ffb9-4e2a-9a7f-51229591077f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read'])[10]/following::div[4]</value>
      <webElementGuid>a947ea35-08ef-4b12-be5a-c01011b74ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Target Peserta'])[2]/following::div[11]</value>
      <webElementGuid>28dac2a1-0fa0-48aa-b598-bb049d7b5862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write'])[10]/preceding::div[1]</value>
      <webElementGuid>e52c64a4-3189-4059-bd18-98071ff3bc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BC Message Template'])[2]/preceding::div[1]</value>
      <webElementGuid>74a9f74f-ab83-4e4b-bbf0-0d627895ae65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-accordion-item[10]/nb-accordion-item-body/div/div/div/div[2]/p-checkbox/div/div[2]</value>
      <webElementGuid>2a58bc3e-6ccd-4029-9a14-6c5679a66b80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
