<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>15 BC Massage Tamplate</name>
   <tag></tag>
   <elementGuidId>047acb44-6b7c-49b4-82cf-b4e2b6297230</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nb-accordion-item-header.ng-tns-c182-58.ng-star-inserted.accordion-item-header-expanded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p-tabpanel-0']/ngx-roles-menus/nb-accordion/nb-accordion-item[11]/nb-accordion-item-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nb-accordion-item-header</value>
      <webElementGuid>59e2b510-f998-4ec0-bfe2-ae5220296095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c182-58 ng-star-inserted accordion-item-header-expanded</value>
      <webElementGuid>f5659a58-f05b-4767-95ef-d4cca83dd430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a03f10a2-3aee-41e2-a4e9-d3e4e42fa113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e4b35041-41a2-47fe-8975-112bc924b4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ac78fcef-5a74-4129-974e-77ad6005bbe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BC Message Template</value>
      <webElementGuid>58b2ed6b-6fb0-40d1-a939-733d131e5af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/ngx-roles-menus[1]/nb-accordion[@class=&quot;box-noshadow&quot;]/nb-accordion-item[@class=&quot;ng-star-inserted expanded&quot;]/nb-accordion-item-header[@class=&quot;ng-tns-c182-58 ng-star-inserted accordion-item-header-expanded&quot;]</value>
      <webElementGuid>59862cb4-6cb5-43c0-b518-adcca5da8f4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-0']/ngx-roles-menus/nb-accordion/nb-accordion-item[11]/nb-accordion-item-header</value>
      <webElementGuid>e458e83a-eb28-441a-9b53-c1fb4b11eabe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write'])[10]/following::nb-accordion-item-header[1]</value>
      <webElementGuid>80e60f33-6b40-4487-8d27-b93b225f1038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read'])[10]/following::nb-accordion-item-header[1]</value>
      <webElementGuid>c9877a4e-17f3-43d9-a6bd-9ce60a009a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read'])[11]/preceding::nb-accordion-item-header[1]</value>
      <webElementGuid>0b8770f0-1731-44e3-8553-c8ded2a4432c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-accordion-item[11]/nb-accordion-item-header</value>
      <webElementGuid>276466ef-ff50-4390-9b13-d4dee9850e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nb-accordion-item-header[(text() = 'BC Message Template' or . = 'BC Message Template')]</value>
      <webElementGuid>908f950c-862f-48f4-b2b2-eec5ff47ad20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
