<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>30 Monitoring Vendor IAK</name>
   <tag></tag>
   <elementGuidId>1fae36ad-b1a0-4699-b1ba-4e86f16ea42a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nb-accordion-item-header.ng-tns-c182-88.ng-star-inserted.accordion-item-header-expanded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p-tabpanel-0']/ngx-roles-menus/nb-accordion/nb-accordion-item[26]/nb-accordion-item-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nb-accordion-item-header</value>
      <webElementGuid>c4bfa647-e490-4d2e-961a-61e12c4028e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c182-88 ng-star-inserted accordion-item-header-expanded</value>
      <webElementGuid>eb0a9716-2834-4617-96ec-7629a2a65755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b7cd123f-c4d9-42c3-bb55-25324d5682e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9403fb1d-841b-4202-9c95-d81e4379b0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f6592e91-27bb-4f93-9c09-d2c2fca10e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Monitoring Vendor IAK</value>
      <webElementGuid>e4aceb2c-2a7e-44ce-9650-2465a599d97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/ngx-roles-menus[1]/nb-accordion[@class=&quot;box-noshadow&quot;]/nb-accordion-item[@class=&quot;ng-star-inserted expanded&quot;]/nb-accordion-item-header[@class=&quot;ng-tns-c182-88 ng-star-inserted accordion-item-header-expanded&quot;]</value>
      <webElementGuid>3bd98d61-6115-455f-b18c-916819af5c97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-0']/ngx-roles-menus/nb-accordion/nb-accordion-item[26]/nb-accordion-item-header</value>
      <webElementGuid>8c7aec03-f036-4a42-9f89-73bcb8c90154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write'])[25]/following::nb-accordion-item-header[1]</value>
      <webElementGuid>b3f988d7-0d07-445e-aeb0-6c5dd6e71a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read'])[25]/following::nb-accordion-item-header[1]</value>
      <webElementGuid>3daf1b43-e206-4e6b-8fcc-d5b81ab7c5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read'])[26]/preceding::nb-accordion-item-header[1]</value>
      <webElementGuid>8bc76ad8-c665-4ad3-a55a-24c1ba413296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-accordion-item[26]/nb-accordion-item-header</value>
      <webElementGuid>05f12976-9e4c-4598-a1c9-9f3c77841d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nb-accordion-item-header[(text() = 'Monitoring Vendor IAK' or . = 'Monitoring Vendor IAK')]</value>
      <webElementGuid>8d50ba41-4a39-42f9-a59c-2ca491b77d86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
