<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>8 Setting Campaign</name>
   <tag></tag>
   <elementGuidId>a630bc71-cead-412f-a23c-fe411fc4e5b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nb-accordion-item-header.ng-tns-c182-44.accordion-item-header-collapsed.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p-tabpanel-0']/ngx-roles-menus/nb-accordion/nb-accordion-item[4]/nb-accordion-item-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nb-accordion-item-header</value>
      <webElementGuid>81d3801c-8d98-47af-ba7f-a8abeebe1c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c182-44 accordion-item-header-collapsed ng-star-inserted</value>
      <webElementGuid>421d9f31-c3b1-4cc9-ab12-4081d7110930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a8208d88-a113-4747-87fe-d4d47cd31d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>60629ae3-f01a-4a0a-a186-2e786cf36a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6dc7d981-653b-467d-87e0-fb5be73ad444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Setting Campaign</value>
      <webElementGuid>3d268d80-7612-4613-a68f-47cc1f260cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/ngx-roles-menus[1]/nb-accordion[@class=&quot;box-noshadow&quot;]/nb-accordion-item[@class=&quot;collapsed ng-star-inserted&quot;]/nb-accordion-item-header[@class=&quot;ng-tns-c182-44 accordion-item-header-collapsed ng-star-inserted&quot;]</value>
      <webElementGuid>a28a2952-c8c3-42c4-a837-09caf03faecd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-0']/ngx-roles-menus/nb-accordion/nb-accordion-item[4]/nb-accordion-item-header</value>
      <webElementGuid>5a1b0548-d7be-40bd-a5c4-b7342d19f34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write'])[3]/following::nb-accordion-item-header[1]</value>
      <webElementGuid>f4e3ae20-c720-4e83-af0d-14974f581244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read'])[3]/following::nb-accordion-item-header[1]</value>
      <webElementGuid>a3055bef-ea2c-4252-bd13-941ea15dc503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read'])[4]/preceding::nb-accordion-item-header[1]</value>
      <webElementGuid>185b4641-296b-477e-b1fb-becdd3807c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-accordion-item[4]/nb-accordion-item-header</value>
      <webElementGuid>186250b7-f31b-41f5-886e-280e44d60ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nb-accordion-item-header[(text() = 'Setting Campaign' or . = 'Setting Campaign')]</value>
      <webElementGuid>c56cf6db-c045-479d-819a-adc135169731</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
