<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>5Click nb-option_Wallet Rupiah MSR</name>
   <tag></tag>
   <elementGuidId>5e2c3eb6-8bf4-4b39-9c5e-4125ed74ea6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nb-option-18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nb-option[@id='nb-option-18']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nb-option</value>
      <webElementGuid>37bc09a3-5d1b-448f-b8cb-af85938fa0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>wallet_rupiah_msr</value>
      <webElementGuid>9ab483b8-51f8-4cd3-a9c4-eb71b6fb35fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6a1f173a-e527-4598-aef8-798c7fbddcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nb-option-18</value>
      <webElementGuid>22d3edf3-d8e1-4ebc-8799-760509cc7486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nb-transition ng-star-inserted</value>
      <webElementGuid>316a5b8b-f545-4091-ae05-a7a8014e247b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wallet Rupiah MSR</value>
      <webElementGuid>c7301788-00cb-4e40-bb96-0b6a144f3bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nb-option-18&quot;)</value>
      <webElementGuid>2958c9ce-67f3-4164-86eb-a290d9507a5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//nb-option[@id='nb-option-18']</value>
      <webElementGuid>74fc7ce4-c763-4092-a337-d829d7f9e5c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-1']/nb-option-list/ul/nb-option[5]</value>
      <webElementGuid>337539b0-7346-412a-a2d5-3a29e8dae976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet Point MSR 2'])[1]/following::nb-option[1]</value>
      <webElementGuid>5a6ee00d-b478-47fd-a929-9ab88434f114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TCNew'])[1]/following::nb-option[2]</value>
      <webElementGuid>51b807ff-92bf-4f20-8914-b8e83c24f1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UNDIAN AKHIR TAHUN MISHIRIN'])[1]/preceding::nb-option[1]</value>
      <webElementGuid>a3c07b3c-02b4-480d-8701-5240e2e3195c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-option[5]</value>
      <webElementGuid>a2bd27a2-ff74-4a99-9331-da352afd1e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nb-option[@id = 'nb-option-18' and (text() = 'Wallet Rupiah MSR' or . = 'Wallet Rupiah MSR')]</value>
      <webElementGuid>242110cc-3fe5-44ce-ac35-00c875d97f40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
