<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>6OB th_Jumlah Produk</name>
   <tag></tag>
   <elementGuidId>cd9f9333-599a-4b3c-882f-6164de56025f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.p-element.p-sortable-column.p-resizable-column.ng-star-inserted.p-highlight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='pr_id_2-table']/thead/tr/th[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>16c8b3de-0390-48ac-a3a2-ebc6e04e3c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element p-sortable-column p-resizable-column ng-star-inserted p-highlight</value>
      <webElementGuid>eed91b79-6df8-4f15-94f2-0f978b6e66f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-field</name>
      <type>Main</type>
      <value>jumlah_produk</value>
      <webElementGuid>a51f53b9-6737-4345-9f17-86181ba0bd9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a0868cd9-a2cf-41f2-ae04-bbe15f728587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>columnheader</value>
      <webElementGuid>194ca520-dc25-4430-a28b-ad65ff26ee71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-sort</name>
      <type>Main</type>
      <value>descending</value>
      <webElementGuid>b1184f4d-860d-45ea-a128-5d9dc1b5228c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Jumlah Produk </value>
      <webElementGuid>de916f6a-def4-4cb2-81ee-43b8c578dfed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_2-table&quot;)/thead[@class=&quot;p-datatable-thead&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/th[@class=&quot;p-element p-sortable-column p-resizable-column ng-star-inserted p-highlight&quot;]</value>
      <webElementGuid>9a4af325-dab3-4835-84d6-4b7d107f87a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pr_id_2-table']/thead/tr/th[3]</value>
      <webElementGuid>83001e99-0c75-4cd9-a24d-9f95cba0c4e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Catalog'])[2]/following::th[1]</value>
      <webElementGuid>868a26b9-4fe7-41a8-a48c-2022c139e910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Catalog'])[2]/following::th[2]</value>
      <webElementGuid>77c2d71b-3569-45c0-8d29-89f4e8e73577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Target Group'])[2]/preceding::th[1]</value>
      <webElementGuid>4a325934-29cc-432b-a7e8-1401a3850543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periode Aktif Catalog'])[2]/preceding::th[2]</value>
      <webElementGuid>46a816da-288f-4b8c-ba65-93dc85424798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-tabpanel[2]/div/div[2]/div/p-table/div/div/table/thead/tr/th[3]</value>
      <webElementGuid>56574c01-21ff-40e2-914e-9241843e0562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = ' Jumlah Produk ' or . = ' Jumlah Produk ')]</value>
      <webElementGuid>3d486cf4-469c-44f4-8e82-74fb16c0bab3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
