<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>22 Click button_Kirim Revisi</name>
   <tag></tag>
   <elementGuidId>e7eeb470-4f07-45f5-b9aa-82ecc58fe8ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.appearance-filled.size-medium.shape-rectangle.status-warning.nb-transition</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-0']/nb-dialog-container/user-detail/div/div/nb-card/nb-card-body/div[5]/div/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>917c7395-1557-4b27-905c-23029ce04cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>status</name>
      <type>Main</type>
      <value>warning</value>
      <webElementGuid>61816e11-b888-44f2-8869-2371c5525d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-status</name>
      <type>Main</type>
      <value>warning</value>
      <webElementGuid>853487a0-fcad-4ce1-8e5e-0638f2ca218a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>30b73288-1fae-491e-9f07-ad457b0f4fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>49d7ed77-50f5-490d-ac7f-c1cccfe5b415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f40e1797-2887-4fef-9b68-f18159953775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>appearance-filled size-medium shape-rectangle status-warning nb-transition</value>
      <webElementGuid>d83b1ec4-4cf3-482b-a563-5372997b7c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Kirim Revisi </value>
      <webElementGuid>0e9845f2-290c-4748-beba-fecea2cbd75d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-0&quot;)/nb-dialog-container[1]/user-detail[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-md-12&quot;]/nb-card[@class=&quot;modals&quot;]/nb-card-body[1]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/button[@class=&quot;appearance-filled size-medium shape-rectangle status-warning nb-transition&quot;]</value>
      <webElementGuid>e423dc34-80d6-4684-a27b-a0bba330e169</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-0']/nb-dialog-container/user-detail/div/div/nb-card/nb-card-body/div[5]/div/div/button[2]</value>
      <webElementGuid>a4a25a6b-b69f-455d-b684-f030b1340064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unverified'])[1]/following::button[1]</value>
      <webElementGuid>469b53c1-758d-4bf9-ab9c-f6f9d5cfbc65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Revisi Data Bank'])[1]/following::button[2]</value>
      <webElementGuid>c4e99f6a-0098-4806-bced-19e601dda513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete User'])[1]/preceding::button[1]</value>
      <webElementGuid>ecdb98fb-d6e5-448f-b70f-5fe020b71b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Similar Data User'])[1]/preceding::button[2]</value>
      <webElementGuid>64aed097-0c2f-4621-9279-b8bca31eca8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kirim Revisi']/parent::*</value>
      <webElementGuid>a233bf84-8890-4d1a-bf2a-c528eaec88f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button[2]</value>
      <webElementGuid>3fd241c6-9cab-45df-8d24-b31874b1cd10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Kirim Revisi ' or . = ' Kirim Revisi ')]</value>
      <webElementGuid>17e7e695-5fd7-48a7-82f5-9a9ea056abb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
