<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>27.6 C WALLET UNDIAN AKHIR TAHUN MISHIRIN</name>
   <tag></tag>
   <elementGuidId>e0d3120a-d26e-4b42-abd1-915cd863c451</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nb-option-195</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nb-option[@id='nb-option-195']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nb-option</value>
      <webElementGuid>c953102b-cddc-42e0-b60a-ea1428992a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>undian_akhir_tahun_mishirin</value>
      <webElementGuid>acc50242-a9e4-4cc5-88bc-41d511477665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>30fb5d83-f46a-4218-b60d-638d63aaa19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nb-option-195</value>
      <webElementGuid>e207938a-aec8-43a9-a0e0-953a473eb2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nb-transition ng-star-inserted</value>
      <webElementGuid>13a5299e-2fea-4209-be19-1981ef0bdfc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UNDIAN AKHIR TAHUN MISHIRIN</value>
      <webElementGuid>030792e4-7725-497f-a101-59d52f9ed557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nb-option-195&quot;)</value>
      <webElementGuid>918a6da9-ffdf-4850-946e-560248a93a90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//nb-option[@id='nb-option-195']</value>
      <webElementGuid>b4cc4848-737b-4484-bd07-d35f302f3e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-33']/nb-option-list/ul/nb-option[6]</value>
      <webElementGuid>a6a35294-1d89-4c70-9a6d-2d29bacc6414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet Rupiah MSR'])[4]/following::nb-option[1]</value>
      <webElementGuid>8a5c90d0-736f-4895-917b-725c58b93871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet Point MSR 2'])[1]/following::nb-option[2]</value>
      <webElementGuid>ecfae7ea-3f47-47e6-8d99-75d5566cac59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet Point MSR'])[1]/preceding::nb-option[1]</value>
      <webElementGuid>8f99a02d-f001-4486-a2b6-4a91e0962cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-option[6]</value>
      <webElementGuid>49b92599-4012-4c25-9cc8-d16227ab5ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nb-option[@id = 'nb-option-195' and (text() = 'UNDIAN AKHIR TAHUN MISHIRIN' or . = 'UNDIAN AKHIR TAHUN MISHIRIN')]</value>
      <webElementGuid>a8c09f4b-7bbf-4b6a-a7dd-dcd34e97b99f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
