<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>37.6 WALLET UNDIAN AKHIR TAHUN MISHIRIN</name>
   <tag></tag>
   <elementGuidId>b70ab80e-66d2-4878-b40e-ca4456b11c15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nb-option-167</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nb-option[@id='nb-option-167']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nb-option</value>
      <webElementGuid>81ece764-ed26-4ea3-89f7-5924b5e7b2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>undian_akhir_tahun_mishirin</value>
      <webElementGuid>94a0389e-ef77-4d50-b347-0e52696927ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e18d567d-2850-412f-905f-f3810b8b78ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nb-option-167</value>
      <webElementGuid>fe3f465c-7f31-4b65-888d-082521fc595b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nb-transition ng-star-inserted</value>
      <webElementGuid>3db1d124-b862-4bc8-89f8-cd1814ba48e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UNDIAN AKHIR TAHUN MISHIRIN</value>
      <webElementGuid>12d9602e-3252-4a1e-b6fe-0d2085ea934c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nb-option-167&quot;)</value>
      <webElementGuid>3dc93ad9-2ccc-48c3-9fb2-f759b0aa24f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//nb-option[@id='nb-option-167']</value>
      <webElementGuid>d3658f76-0f63-47fd-8558-37cadbce4bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-35']/nb-option-list/ul/nb-option[6]</value>
      <webElementGuid>7d9b1806-d631-4662-bd33-809aa6b2ca98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet Rupiah MSR'])[5]/following::nb-option[1]</value>
      <webElementGuid>dde3c470-2b52-42c7-809d-fc46abb9e66e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet Point MSR 2'])[1]/following::nb-option[2]</value>
      <webElementGuid>036f8f02-14c0-48e8-b936-cf75f39782de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet Point MSR'])[1]/preceding::nb-option[1]</value>
      <webElementGuid>91f58045-7323-40f2-b239-e89cb55feeec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-option[6]</value>
      <webElementGuid>c6c7ec9b-1589-49b0-b119-02bd04182d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nb-option[@id = 'nb-option-167' and (text() = 'UNDIAN AKHIR TAHUN MISHIRIN' or . = 'UNDIAN AKHIR TAHUN MISHIRIN')]</value>
      <webElementGuid>77c27261-eb47-4b4b-be20-ef0a125f6e8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
