<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>4.1 C 1 PERIODE UNTUK MENDAPATKAN REWARD ATURAN1</name>
   <tag></tag>
   <elementGuidId>99ca3eb1-f759-4b89-ad05-837040030459</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nb-option-175</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nb-option[@id='nb-option-175']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nb-option</value>
      <webElementGuid>dd922440-545d-478e-8803-b3b6686bed0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6852f5cf-81f8-4e82-8a73-4674a0c90de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4dbaec72-1137-4db6-8946-8889c9d34aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nb-option-175</value>
      <webElementGuid>89ab2a80-bd60-4bc5-a83d-0c2f65ac792b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nb-transition ng-star-inserted</value>
      <webElementGuid>7e8a8613-462a-48bd-ba09-1d5f0c100114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>209703a9-9328-4b0a-9a37-e6c6306ac8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nb-option-175&quot;)</value>
      <webElementGuid>916c2f8f-70ed-45f1-88ee-9087deba00c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//nb-option[@id='nb-option-175']</value>
      <webElementGuid>34e097d3-b9c0-42c1-ba68-dc01ac52c923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-26']/nb-option-list/ul/nb-option</value>
      <webElementGuid>b5ab658f-825f-4fe0-89b0-479bcee9d5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim'])[1]/following::nb-option[1]</value>
      <webElementGuid>c6f7193b-b0e3-4822-98ef-93cb85f66071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::nb-option[2]</value>
      <webElementGuid>f316e970-4776-4e55-a5e2-59819c9a3800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::nb-option[2]</value>
      <webElementGuid>376b1e80-e52f-4ce4-a90f-58ac66881651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-option</value>
      <webElementGuid>0c123811-eb22-44b0-8895-1f70ab3bfbf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nb-option[@id = 'nb-option-175' and (text() = '1' or . = '1')]</value>
      <webElementGuid>61dde56a-af78-45f0-9cad-93b5fbc5f907</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
