<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_user-msr-1</name>
   <tag></tag>
   <elementGuidId>018aa4c5-222d-4399-8a6c-5be7159b0e25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nb-option-40 > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='senen'])[1]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2032e7f1-4181-456f-a578-dda9c4a27f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>user-msr-1</value>
      <webElementGuid>568d6547-ad45-4e95-967c-25f05b2c5d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nb-option-40&quot;)/div[1]</value>
      <webElementGuid>f8ef0ad7-11b9-41a2-9a6d-c8a52f8c94c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nb-option[@id='nb-option-40']/div</value>
      <webElementGuid>528cb69a-d558-4943-a6eb-e596ff74b873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='senen'])[1]/following::div[1]</value>
      <webElementGuid>a1d456e9-e41a-4159-9ab5-d4e5e9738127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='provinsi-msr-2'])[1]/following::div[2]</value>
      <webElementGuid>2ccbe090-f02e-40e1-a677-3714460864d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'nb-option-40', '&quot;', ')/div[1]')])[1]/preceding::div[8]</value>
      <webElementGuid>1e58a208-d2c1-40d8-9615-02d8dd0b21a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='user-msr-1']/parent::*</value>
      <webElementGuid>ce015938-e693-4fb1-8743-7ffddc9238cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-option[15]/div</value>
      <webElementGuid>af839a32-5656-44c3-a3fe-a351884c3b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'user-msr-1' or . = 'user-msr-1')]</value>
      <webElementGuid>60e60b34-c4f1-4614-99be-82f08ec8821c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
