<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email address_email</name>
   <tag></tag>
   <elementGuidId>624fe7ac-a5da-4efe-b5a6-66b41d0fcddb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2488363-5256-4edc-a361-4673c8ff00fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>25aa516b-a671-4ad3-8381-071a50607361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-email</value>
      <webElementGuid>9bd1fd9c-9881-44b4-aa13-fe0bc2cbd0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>.+@.+\..+</value>
      <webElementGuid>60db8e61-0e4c-4c54-8ff7-530127de5a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email address</value>
      <webElementGuid>3805f21c-3d0a-4bce-a2fb-a3fdd3bcd8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-valid ng-touched</value>
      <webElementGuid>b64dce62-67c2-4ab3-a3a6-800d7227dc4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-pattern</name>
      <type>Main</type>
      <value>.+@.+\..+</value>
      <webElementGuid>c389295c-6c2b-4502-94a0-8533b30ea21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>f9dc5c59-e420-4e58-a0ab-587710a7419b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-email&quot;)</value>
      <webElementGuid>a388fbbf-2094-4229-a29f-bedcb37fd30d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-email']</value>
      <webElementGuid>bde6250a-198a-4e1f-8290-ee3694aa8d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0ae3df49-84ad-4fea-97f2-6e7c25cb0fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email' and @id = 'input-email' and @placeholder = 'Email address']</value>
      <webElementGuid>b7e64cfa-2ff4-4f0d-b28f-c7dd6ca4f441</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
