<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>11Click button_Edit</name>
   <tag></tag>
   <elementGuidId>10253b9c-d10f-4fa9-ae71-10f704ce70a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button-confirmation-modal.appearance-filled.full-width.size-medium.shape-rectangle.status-primary.nb-transition</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[45]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2c1265c3-da9f-4105-8e14-0d3e3dafdb57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52215157-a042-4079-92c7-110d368e9f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>581b1402-7ce2-4529-9453-e98043432d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nbspinnerstatus</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>734d1582-2fba-4bc0-b8ba-7ec714489f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-confirmation-modal appearance-filled full-width size-medium shape-rectangle status-primary nb-transition</value>
      <webElementGuid>249f683f-40fa-40ed-ac6b-f54edac60eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>5602b021-d9c9-433f-a8dc-08870161865b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-spinner-status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>ffccc44c-e045-4555-bef1-e6cacc41d8a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4ff4ac8f-0f1b-46a5-962b-8c009715c768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-nb-spinner</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>68f67a06-2deb-4bcd-9438-129d0e777b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>11b547d3-331c-4d90-9389-a0f272776a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d4ddd73e-c6d5-4585-bfea-52d4041ac8e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Edit </value>
      <webElementGuid>aaa98886-b992-4ae4-a082-c7e17c4bada4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-4&quot;)/nb-dialog-container[1]/form-kabupaten-group[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/nb-card[1]/nb-card-body[1]/form[@class=&quot;ng-pristine ng-valid ng-touched&quot;]/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-md-12&quot;]/button[@class=&quot;button-confirmation-modal appearance-filled full-width size-medium shape-rectangle status-primary nb-transition&quot;]</value>
      <webElementGuid>7e42a3c2-a7d3-4353-9305-4023cd731726</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[45]</value>
      <webElementGuid>b6d6e076-fa88-482b-ba1c-0c860e3b070f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-4']/nb-dialog-container/form-kabupaten-group/div/div/nb-card/nb-card-body/form/div[4]/div/button</value>
      <webElementGuid>5d514298-8ecc-46af-b3f8-f91f485a20c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add District Coverage'])[1]/following::button[1]</value>
      <webElementGuid>655c82f5-5bb2-4502-b086-16ee11e64f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Southwest Aceh District'])[1]/following::button[6]</value>
      <webElementGuid>6a59d47b-12de-481f-b40b-0fc03114ce83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Original text'])[1]/preceding::button[1]</value>
      <webElementGuid>84734e67-8531-473a-b0ad-c620dd1abf5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rate this translation'])[1]/preceding::button[1]</value>
      <webElementGuid>3e4e5e80-18ad-4bf7-8005-b41e4c76aa46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>75321ea3-dc8b-401b-90d6-7957aa4e43fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>25502556-0b79-4d54-823c-ffb1909999b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Edit ' or . = ' Edit ')]</value>
      <webElementGuid>3c18f790-eefb-404b-b075-b68d2711d8c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
