<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>1Click button_Add New Group</name>
   <tag></tag>
   <elementGuidId>e2a9100b-9025-4c29-ae6d-e144d2b6b677</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>kabupaten-group > div.row > div.col-md-12 > button.mb-2.appearance-filled.size-small.shape-round.icon-start.status-primary.nb-transition</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[28]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d06c61c1-4568-4339-b46a-88167949587f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7fd8d1db-825b-4d25-93d5-72a0e8fb7560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>094bce2b-9fe2-499f-bb59-a65d1a2bde13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>6dd234b5-08b5-4e66-a114-9922abba708f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>e37edc26-ae1a-4814-8669-15f3fcbb2f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2 appearance-filled size-small shape-round icon-start status-primary nb-transition</value>
      <webElementGuid>5831dcef-0edc-4dc3-b52d-48c51869f126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-size</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>31e50928-aa72-4f84-bac0-d727e781f668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-shape</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>8817a8f1-18b1-4988-9c6f-80381871c09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>cc77645e-2889-416a-8022-4e79e43347c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>da24e423-3e36-4721-8a7d-daf38d5a9b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5ac7a1de-da9b-44d1-b086-f43a0459e80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add New Group</value>
      <webElementGuid>5a2f3d91-3ac4-4e21-82c2-bfe27e52e65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-2&quot;)/kabupaten-group[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/button[@class=&quot;mb-2 appearance-filled size-small shape-round icon-start status-primary nb-transition&quot;]</value>
      <webElementGuid>5c350af2-13e5-4815-8d67-22f51af7f754</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[28]</value>
      <webElementGuid>b6f1e6ef-7bec-4dad-93a3-4a90a085bbff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-2']/kabupaten-group/div/div/button</value>
      <webElementGuid>dce2c156-04d0-4143-ac13-1daad8ffced2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Provinsi MSR 2'])[1]/following::button[6]</value>
      <webElementGuid>56b1041e-7f58-4416-8349-5362283e2079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='provinsi-msr-2'])[1]/following::button[6]</value>
      <webElementGuid>f554f2a3-3a79-4399-8650-d16ce9ef15fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group ID'])[4]/preceding::button[1]</value>
      <webElementGuid>14811dee-6d5b-4ca3-8b5b-3c9a6e54946d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kabupaten-group/div/div/button</value>
      <webElementGuid>d4d3085f-dabe-41ba-a770-079c3e86494f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Add New Group' or . = 'Add New Group')]</value>
      <webElementGuid>3c2e6c30-5747-4456-9787-ab5b29e2ab51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
