<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>4Samediv__col-md-2</name>
   <tag></tag>
   <elementGuidId>462cf791-b01e-458d-a081-c8f193deb8a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-md-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p-tabpanel-1']/div/nb-card/nb-card-body/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7dfafc18-b8ae-460d-9bf8-ff490f50fb70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>4ede8be2-b6c3-4f6c-bb73-a279c9078235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-2</value>
      <webElementGuid>5a39eb41-e874-4630-9def-c3e7160e7a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-1&quot;)/div[@class=&quot;ng-star-inserted&quot;]/nb-card[@class=&quot;mt-4 ng-star-inserted&quot;]/nb-card-body[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-2&quot;]</value>
      <webElementGuid>183b71c1-e293-43bb-b82f-7ccb6ce6f493</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-1']/div/nb-card/nb-card-body/div/div[2]</value>
      <webElementGuid>28c9ed99-a5a9-4743-9878-aad2f6ffd2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='...'])[1]/following::div[1]</value>
      <webElementGuid>56f2249b-b920-4a0d-a9fc-6ac6572a4af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ONLINE / Livestreaming'])[1]/following::div[1]</value>
      <webElementGuid>41fefb80-66ce-4434-a891-0fed6aaaef12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group Peserta: user-msr-1'])[2]/preceding::div[1]</value>
      <webElementGuid>400a53b3-3cb3-46fc-9334-78a50304d822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terdapat Pesan yang belum terkirim'])[2]/preceding::div[4]</value>
      <webElementGuid>02359aac-e659-46a6-b1a4-c002d390efaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-card-body/div/div[2]</value>
      <webElementGuid>41488d9e-a9b8-4be8-80b6-04c384304f4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
