<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>12ST input_Nama Pemilik_filter-nama_pemilik</name>
   <tag></tag>
   <elementGuidId>ea9f8835-e455-4f88-9b04-7d5ed65cfe73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter-nama_pemilik</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter-nama_pemilik']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9095fd1e-91cb-451f-9c24-247b0158bbed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>c0de05f7-ce63-4d68-9898-0ce3fe6a52b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a9f20bcf-3e1a-4d97-bd55-0b6f5129da75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>652f3e1d-849a-4d4a-989e-22007bb93d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter-nama_pemilik</value>
      <webElementGuid>6e48c45d-901f-4f68-b4e2-49f0f2b7438e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Pemilik</value>
      <webElementGuid>7c75fa11-fe44-4a89-a4f9-8b6a3f72c8e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-full-width size-medium status-primary shape-rectangle nb-transition cdk-focused cdk-mouse-focused</value>
      <webElementGuid>d7cd4a0d-640a-4df3-9fba-80e599c2ceb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-nama_pemilik&quot;)</value>
      <webElementGuid>8c4aaf79-5e7e-4474-a918-3ab24a132339</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter-nama_pemilik']</value>
      <webElementGuid>575751cf-b500-4224-b357-d69cb2f87673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-6']/nb-dialog-container/browse-user-for-cakupan/div/div/nb-card/nb-card-body/div/div[2]/nb-card/nb-card-body/div[2]/div/div/input</value>
      <webElementGuid>bfe11be1-7192-43fd-8ecf-5fdfd0aa142a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>76a958a9-6dbf-474b-905f-5d6f264b540c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'filter-nama_pemilik' and @placeholder = 'Nama Pemilik']</value>
      <webElementGuid>546b9614-cc29-40aa-95b3-4a3c80fc403a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
