<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>8Click button_Browse User</name>
   <tag></tag>
   <elementGuidId>63264e3c-1894-4863-acf7-f34139943550</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-md-2.mt-3 > button.mb-2.appearance-outline.size-small.shape-rectangle.icon-start.status-primary.nb-transition</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p-tabpanel-0']/user-group/nb-tabset/nb-tab[2]/user-tags-md/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e37d77d-b414-4ce0-8c55-289f9007135e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>c01691ef-bf8f-4245-a814-49c9b3159262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>9320d2b8-3be4-40eb-8a7a-0d3a8ebea54f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2 appearance-outline size-small shape-rectangle icon-start status-primary nb-transition</value>
      <webElementGuid>26e9e92c-b9b0-4509-96bf-c9e45c15d75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-size</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>fe201271-bda8-4d0f-9b92-7adb535a64ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-status</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>b6819ffb-2c48-45e9-9d4d-8b4a64091233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>99cdc327-06ab-43f4-8472-73001e4c65f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e0b746ac-ff53-47a4-9c81-89847fcf6928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d70724a1-d36f-4eaa-8755-6b344a6f0f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Browse User </value>
      <webElementGuid>341c1298-174b-4521-8c79-3cd044ff869e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/user-group[1]/nb-tabset[1]/nb-tab[@class=&quot;content-active&quot;]/user-tags-md[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row mt-2&quot;]/div[@class=&quot;col-md-2 mt-3&quot;]/button[@class=&quot;mb-2 appearance-outline size-small shape-rectangle icon-start status-primary nb-transition&quot;]</value>
      <webElementGuid>e7f74368-460f-43d8-8acd-86515a90e923</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-0']/user-group/nb-tabset/nb-tab[2]/user-tags-md/div/div/button</value>
      <webElementGuid>90399ad6-73a5-4f4d-ab13-173a28e5bd62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ridwan owner | wijayadell789@gmail.com'])[1]/following::button[5]</value>
      <webElementGuid>42cd8105-3709-4fb2-a961-dcbcd6c80b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Toko | Email'])[1]/following::button[5]</value>
      <webElementGuid>67598456-97aa-44bd-a82f-ce6a1c2abf1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAKARTA'])[1]/preceding::button[1]</value>
      <webElementGuid>cf0d6bd4-9854-418f-8099-cc63e07c0908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAKARTA'])[2]/preceding::button[2]</value>
      <webElementGuid>f548ddb4-3d9c-4974-a8a0-084cd587794d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//user-tags-md/div/div/button</value>
      <webElementGuid>10f65a5d-0892-4c62-a12f-339d0e15efa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Browse User ' or . = 'Browse User ')]</value>
      <webElementGuid>c7f2b097-b58e-4195-a19b-77ab0a798333</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
