<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>3ST End Date</name>
   <tag></tag>
   <elementGuidId>bff942b1-7df0-490b-8ec3-c6034db821b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='date'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6e0af7b-16f3-4610-be18-3fd3a38db96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>eda31621-6db3-4a57-bc91-4293d6b67a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>2023-07-12</value>
      <webElementGuid>577f222e-1ea0-46b9-a821-ff776a1e4256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid size-medium status-basic shape-rectangle nb-transition</value>
      <webElementGuid>f4c40a39-da55-4b1a-83cf-e3cc341033ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-1&quot;)/div[@class=&quot;row my-2&quot;]/div[@class=&quot;col-md&quot;]/input[@class=&quot;ng-untouched ng-pristine ng-valid size-medium status-basic shape-rectangle nb-transition&quot;]</value>
      <webElementGuid>cceaf11a-1432-4953-bc35-d6a353731478</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='date'])[4]</value>
      <webElementGuid>d0586aed-5662-4b05-b677-55a5009dbfac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-1']/div[2]/div[4]/input[2]</value>
      <webElementGuid>f44b5497-f9b0-4543-a259-6e1dcdbea603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-tabpanel[2]/div/div[2]/div[4]/input[2]</value>
      <webElementGuid>2094ae3b-26c3-4ee3-9a08-63bb39d54fe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date']</value>
      <webElementGuid>6dc03699-15fa-49e6-8dd1-cf31fbe328e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
