<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nb-option_JAKARTA_1_2_3</name>
   <tag></tag>
   <elementGuidId>05abdfe2-abe0-4ab2-af2c-22eff0201f35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nb-option-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nb-option[@id='nb-option-8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nb-option</value>
      <webElementGuid>25cad403-da68-4956-819e-ccd579bedb82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>JAKARTA</value>
      <webElementGuid>b736ce8f-8a4f-46aa-ae43-db8176ca15f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a0dea4bf-e4c6-4f14-89d5-cd94c83d26ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nb-option-8</value>
      <webElementGuid>855f5907-97e9-4cac-9b35-c41ea3347df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nb-transition ng-star-inserted</value>
      <webElementGuid>4db7c2cb-799e-489f-9c13-55f894d7af7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> JAKARTA </value>
      <webElementGuid>23828c3d-0f29-4caa-a5fd-b2a19fc2bd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nb-option-8&quot;)</value>
      <webElementGuid>98efd454-bb51-4a2c-835b-a8e63d16b566</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//nb-option[@id='nb-option-8']</value>
      <webElementGuid>a2ed22d3-134e-4ab9-95f5-d9eb7c5e7fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-1']/nb-option-list/ul/nb-option</value>
      <webElementGuid>fa2c4507-47f1-4c4a-a1c4-a9da8dc0a56f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Pemenang Peringkat Test Sonny QR'])[1]/following::nb-option[1]</value>
      <webElementGuid>39f57aae-917a-44ca-afec-3fabb5ee6d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAKARTA-OTL'])[1]/preceding::nb-option[1]</value>
      <webElementGuid>c38f7eef-1ab8-4da8-93f1-c87846ba5989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'nb-option-8', '&quot;', ')')])[1]/preceding::nb-option[2]</value>
      <webElementGuid>34e312c3-c567-4d5d-a281-b4b472246259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-option</value>
      <webElementGuid>3ef24c81-12b1-43fc-9048-b54ae5d2405f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nb-option[@id = 'nb-option-8' and (text() = ' JAKARTA ' or . = ' JAKARTA ')]</value>
      <webElementGuid>354cfb14-a115-4710-a28f-4b0aa324b91a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
