<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nb-option_JAKARTATEST2</name>
   <tag></tag>
   <elementGuidId>bf3ea763-c5a0-47a6-8ec3-92cfd1a2ee6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nb-option-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nb-option[@id='nb-option-12']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nb-option</value>
      <webElementGuid>f141766b-e961-4da0-858f-fde29a079e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>JAKARTA@TEST2</value>
      <webElementGuid>882aafdf-819d-4bed-a0f7-aff4945cec66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0e40a287-0de6-4a25-adb2-4912898a5e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nb-option-12</value>
      <webElementGuid>013c5516-c821-4988-a03f-ac9ebe99eac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nb-transition ng-star-inserted</value>
      <webElementGuid>51f05c92-da8e-43bb-ba97-e1d33fd945fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> JAKARTA@TEST2 </value>
      <webElementGuid>b66d0e6d-fff3-481c-95c7-393470435e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nb-option-12&quot;)</value>
      <webElementGuid>87baf711-19bc-4c26-b039-8f2d13778be6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//nb-option[@id='nb-option-12']</value>
      <webElementGuid>91cdacba-5338-4e04-8ed9-fe66699007aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-4']/nb-option-list/ul/nb-option</value>
      <webElementGuid>b8d2455e-2279-4e09-8c8c-3d7d5f76964d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Pemenang Peringkat Test Sonny QR'])[1]/following::nb-option[1]</value>
      <webElementGuid>16891f9d-a9a5-4c09-885b-0c4a266ffd27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'nb-option-12', '&quot;', ')')])[1]/preceding::nb-option[1]</value>
      <webElementGuid>a45aeab0-b53f-4974-8511-2998eb65be95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JAKARTA@TEST2']/parent::*</value>
      <webElementGuid>7b28919c-caa0-4fd3-b92b-0059637bbe54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-option</value>
      <webElementGuid>46d982e8-d783-4e08-8826-bc0517224270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nb-option[@id = 'nb-option-12' and (text() = ' JAKARTA@TEST2 ' or . = ' JAKARTA@TEST2 ')]</value>
      <webElementGuid>05128b3b-e29d-4dcd-a589-9d0d9cdbba24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
