<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p-checkbox_Email_tags-md</name>
   <tag></tag>
   <elementGuidId>3f0eb671-e938-4aac-ab78-d554eab48cb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p-checkbox[name=&quot;tags-md&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p-checkbox[@name='tags-md']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p-checkbox</value>
      <webElementGuid>e31c264b-8bfb-4bf3-bda4-d3e9f39ada35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tags-md</value>
      <webElementGuid>bfe86a63-ca02-442c-831a-6c95522b773b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element ng-untouched ng-pristine</value>
      <webElementGuid>e3858514-b0e5-4d71-a8c2-9774c08dcb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>tags-md</value>
      <webElementGuid>5aa91518-f6b1-40f1-91e8-32f36a918c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-binary</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>52a76af7-7082-4686-92a5-23656e86e751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>09b3e11f-8558-44e9-88b7-bec20438e4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-disabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8b6a3074-1fbf-4d16-8b64-3f496c9298ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-is-disabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ddea0519-a4d5-40fe-895f-c63cd60c5634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_7-table&quot;)/tbody[@class=&quot;p-element p-datatable-tbody&quot;]/tr[@class=&quot;p-element ng-star-inserted&quot;]/td[1]/p-checkbox[@class=&quot;p-element ng-untouched ng-pristine&quot;]</value>
      <webElementGuid>2846e657-3fe4-41d0-8c2a-91967070785e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p-checkbox[@name='tags-md']</value>
      <webElementGuid>d1de3f3b-2f6c-440f-8bbe-3fbb543ebea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pr_id_7-table']/tbody/tr/td/p-checkbox</value>
      <webElementGuid>98c23b14-a40d-4ddf-8fb3-7587fb85f02f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[2]/following::p-checkbox[1]</value>
      <webElementGuid>ea54c351-9bfc-414b-8942-67dee8953fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provinsi'])[2]/following::p-checkbox[1]</value>
      <webElementGuid>40d06d55-af6c-4d3e-aa29-ce997e33fe5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='subdealer'])[1]/preceding::p-checkbox[1]</value>
      <webElementGuid>18c7ad39-ced6-474c-8901-16a471502db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-checkbox</value>
      <webElementGuid>d43f9eb7-7d31-4120-83b4-b8491c130478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p-checkbox[@name = 'tags-md']</value>
      <webElementGuid>9d0ae8b9-c920-4b3d-aca8-c8d1c97a3033</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
