<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>11Click button_-- Pilih Tipe Transaksi --</name>
   <tag></tag>
   <elementGuidId>9fc14ace-673c-4ac4-9b6d-7ff79b63910a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.select-button.placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9231169c-c01f-4692-acf8-4c00b367a0f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c5ea4c46-4f05-4d74-bdbc-b78dac76d651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-button placeholder</value>
      <webElementGuid>feaed1cd-b4b4-4dc4-a864-0150c8fcfa0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>placeholder</value>
      <webElementGuid>b5834c1e-95a1-4399-b132-de1de9c7db73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Tipe Transaksi --</value>
      <webElementGuid>6c35a158-89d3-49cd-bf46-586243a9af62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-7&quot;)/nb-dialog-container[1]/form-wallet-transaction[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/nb-card[1]/nb-card-body[1]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;row p-3&quot;]/div[@class=&quot;col-md-12&quot;]/nb-select[@class=&quot;appearance-outline full-width size-medium status-primary shape-rectangle ng-untouched ng-pristine ng-invalid nb-transition&quot;]/button[@class=&quot;select-button placeholder&quot;]</value>
      <webElementGuid>b170ae74-a1b0-411d-abc9-1cec65b9e6c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[11]</value>
      <webElementGuid>a4995d95-ad55-41e7-af41-a7044c459770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-7']/nb-dialog-container/form-wallet-transaction/div/div/nb-card/nb-card-body/form/div/div/nb-select/button</value>
      <webElementGuid>9d71f5fb-ca3c-4cca-895e-6eb9d204d06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Transaksi'])[2]/following::button[1]</value>
      <webElementGuid>d5eea762-f8c5-4a85-90ba-1cfc2f1f0b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Transaksi'])[2]/following::button[1]</value>
      <webElementGuid>1f2da3b1-4f1f-45dd-924e-c40f55355967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes'])[2]/preceding::button[1]</value>
      <webElementGuid>f7f1bf03-c688-454e-aab8-4c23e2c836b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/nb-select/button</value>
      <webElementGuid>1813ae25-085c-4ae5-838d-50cc25561813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '-- Pilih Tipe Transaksi --' or . = '-- Pilih Tipe Transaksi --')]</value>
      <webElementGuid>d06994bd-3f8c-48b5-a73a-1364a264b8db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
