<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>3Click OB th_Nama</name>
   <tag></tag>
   <elementGuidId>41341977-749b-4856-a30f-eda835361cb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.p-element.p-sortable-column.p-highlight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='pr_id_1-table']/thead/tr/th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>0a68ea98-e6ad-4608-947e-1ae6e8a4752f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element p-sortable-column p-highlight</value>
      <webElementGuid>df0239fb-66dc-4272-ad67-3ee2d52cd73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-field</name>
      <type>Main</type>
      <value>nama_toko</value>
      <webElementGuid>97d64b2c-f3f9-4f56-acfe-12bf51a83a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d3dc85ae-a7b3-4d48-a71c-9e304205296b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>columnheader</value>
      <webElementGuid>8bd30954-6184-4fda-be08-688dcf970f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-sort</name>
      <type>Main</type>
      <value>ascending</value>
      <webElementGuid>a2e4f817-75b0-4658-8479-435cb359fcbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nama</value>
      <webElementGuid>49c6df7c-d761-4def-a5ee-5ac7cd5ef0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_1-table&quot;)/thead[@class=&quot;p-datatable-thead&quot;]/tr[1]/th[@class=&quot;p-element p-sortable-column p-highlight&quot;]</value>
      <webElementGuid>7805d237-9d1c-4c36-b3ad-0f93930c07b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pr_id_1-table']/thead/tr/th</value>
      <webElementGuid>f44c2a42-5019-40a0-a18d-2e37bea83db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search with ...'])[1]/following::th[1]</value>
      <webElementGuid>97bb4ff1-7f1a-4652-8e0c-8e227c0ce9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse Data User'])[1]/following::th[1]</value>
      <webElementGuid>5191b520-2a98-4b3c-b2fe-581e0c429c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Peserta'])[1]/preceding::th[1]</value>
      <webElementGuid>edcd6217-fea4-4d5b-a0a0-2542015098ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Telepon'])[1]/preceding::th[2]</value>
      <webElementGuid>bb9f1cc3-d457-4681-b1c7-0fc13137d34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nama']/parent::*</value>
      <webElementGuid>6581751d-97ff-4d80-bde7-65f5342ccd77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th</value>
      <webElementGuid>d032050e-afad-42cb-a574-394afad422d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Nama' or . = 'Nama')]</value>
      <webElementGuid>5bcdeb32-3fe2-4337-9eb1-eb80b466a0e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
