<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>4Click nb-option_Kabupaten</name>
   <tag></tag>
   <elementGuidId>64a9be6a-b776-4f18-a1a8-661d40b8cb84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nb-option-16</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nb-option[@id='nb-option-16']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nb-option</value>
      <webElementGuid>7cff60bd-c151-44b4-9fe5-c19ce1a8e216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>kabupaten</value>
      <webElementGuid>b9734fbf-141a-4437-a283-8a6bfe636cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>kabupaten</value>
      <webElementGuid>c00beadc-833c-43ef-949f-417311e2aaa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e4fffe5b-111e-45ff-8880-1495739530f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nb-option-16</value>
      <webElementGuid>3b61ecb2-954b-4144-9e67-5fb7cc784e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nb-transition</value>
      <webElementGuid>4a7284ef-b998-4aab-adc1-894529a5d98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Kabupaten</value>
      <webElementGuid>05710b65-6413-4cd2-9190-9af03e2799f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nb-option-16&quot;)</value>
      <webElementGuid>6293e70f-36a5-4dfd-95cc-dc665906e543</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//nb-option[@id='nb-option-16']</value>
      <webElementGuid>cfa4703a-2a1b-4073-879d-57e962513b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-0']/nb-option-list/ul/nb-option[4]</value>
      <webElementGuid>7b8d7181-a712-4fbe-9f04-d85deb3ed0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[6]/following::nb-option[1]</value>
      <webElementGuid>2dd2ad7c-e694-4268-b2ac-231e8eb84c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Pemilik'])[6]/following::nb-option[2]</value>
      <webElementGuid>1805f1d1-1ffc-4c26-9f06-96bf3c119eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::nb-option[1]</value>
      <webElementGuid>ad904a90-6fdb-474d-b15f-fb3fbebcbe23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::nb-option[1]</value>
      <webElementGuid>714b6eb5-2798-4d77-81be-71f693ca0990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kabupaten']/parent::*</value>
      <webElementGuid>e305a3ae-1b33-4941-8b1d-e9fca041d532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nb-option[4]</value>
      <webElementGuid>0aebe2d0-e327-485c-890c-03824e03e95d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nb-option[@id = 'nb-option-16' and (text() = ' Kabupaten' or . = ' Kabupaten')]</value>
      <webElementGuid>c3f52ee7-192d-4fde-bc14-6919882f4159</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
