<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Verifikasi Peserta</name>
   <tag></tag>
   <elementGuidId>034d6ee0-48c1-4e63-8d27-84f8bf9e33ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ng-tns-c140-18.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ngx-one-column-layout[@id='body']/nb-layout/div/div/div/nb-sidebar/div/div/nb-menu/ul/li[4]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1df55cac-c50a-40e8-969e-39c4187eb16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c140-18 ng-star-inserted</value>
      <webElementGuid>f3840ef6-96c0-40ae-a26b-7266aefc5f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/pages/administration/userveri</value>
      <webElementGuid>35c113f2-5bba-4b3b-b40a-6866e049e50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Verifikasi Peserta</value>
      <webElementGuid>e9b65f3a-ffd2-4a65-a02a-1ad1dc09cbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/pages/administration/userverification</value>
      <webElementGuid>202d98e4-ea49-4e5b-aa52-d5d1c696d486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verifikasi Peserta</value>
      <webElementGuid>1b2df284-567d-4f73-b828-1a233520b772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/nb-layout[@class=&quot;window-mode with-scroll&quot;]/div[@class=&quot;scrollable-container&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;layout-container&quot;]/nb-sidebar[@class=&quot;menu-sidebar left expanded&quot;]/div[@class=&quot;main-container main-container-fixed&quot;]/div[@class=&quot;scrollable&quot;]/nb-menu[1]/ul[@class=&quot;menu-items&quot;]/li[@class=&quot;menu-item ng-tns-c140-15 ng-star-inserted&quot;]/ul[@class=&quot;menu-items ng-tns-c140-15 ng-trigger ng-trigger-toggle ng-star-inserted expanded&quot;]/li[@class=&quot;menu-item ng-tns-c140-18 ng-tns-c140-15 ng-star-inserted&quot;]/a[@class=&quot;ng-tns-c140-18 ng-star-inserted&quot;]</value>
      <webElementGuid>9231e433-4e60-4df4-8887-406aad8cbd1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ngx-one-column-layout[@id='body']/nb-layout/div/div/div/nb-sidebar/div/div/nb-menu/ul/li[4]/ul/li[2]/a</value>
      <webElementGuid>d23f4339-72b0-44fb-882c-50240bf3ad38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Mishirin'])[1]/following::a[1]</value>
      <webElementGuid>70ddd36b-6c41-43d2-a883-cd62c74dd66f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create User Internal'])[1]/following::a[2]</value>
      <webElementGuid>78e84afd-f8a9-40b8-9f25-183b9f6e1bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reward Verification'])[1]/preceding::a[1]</value>
      <webElementGuid>c67095f3-c1ad-44d1-b809-5cb1ed81f98f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/pages/administration/userverification')]</value>
      <webElementGuid>4dcec4cc-9dc9-4096-b8c4-d7c3b50c8abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[2]/a</value>
      <webElementGuid>8b6ae022-f23e-40cf-a47f-a274d952f80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Verifikasi Peserta' and @href = '#/pages/administration/userverification' and (text() = 'Verifikasi Peserta' or . = 'Verifikasi Peserta')]</value>
      <webElementGuid>6a152e4a-bda7-46c1-a156-638481bb6613</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
