<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>10OBTotalVisit</name>
   <tag></tag>
   <elementGuidId>a286cd19-bf3e-44a0-b507-1c55933bdd21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='pr_id_1-table']/thead/tr/th[3]/div/p-sorticon/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.justify-content-between.align-items-center.text-center > p-sorticon.p-element > i.p-sortable-column-icon.pi.pi-fw.pi-sort-alt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9da26990-6053-463d-a889-9ed9cb9debfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-sortable-column-icon pi pi-fw pi-sort-alt</value>
      <webElementGuid>179c1cf9-7e84-4427-ada1-f029e966044c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>140cc7b2-078f-4c3e-88dc-d3f4447e1e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_1-table&quot;)/thead[@class=&quot;p-datatable-thead&quot;]/tr[@class=&quot;no-highlight ng-star-inserted&quot;]/th[@class=&quot;p-element p-sortable-column&quot;]/div[@class=&quot;flex justify-content-between align-items-center text-center&quot;]/p-sorticon[@class=&quot;p-element&quot;]/i[@class=&quot;p-sortable-column-icon pi pi-fw pi-sort-alt&quot;]</value>
      <webElementGuid>365af64b-8d1a-44e6-9a02-b8288c5ab319</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pr_id_1-table']/thead/tr/th[3]/div/p-sorticon/i</value>
      <webElementGuid>bec9f583-609d-4b0c-951a-8dca0bb7c282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/div/p-sorticon/i</value>
      <webElementGuid>66a065bf-ebe5-4ab2-9a1c-b3d5dd14c3bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
