<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_1</name>
   <tag></tag>
   <elementGuidId>c135427a-02a2-442c-8992-cbdc09377fdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.eva.eva-close-square-outline > g > g > rect</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>ecfecdb2-a15f-45ef-853f-c0506be0ffbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>db4b6402-b054-4b9f-bdfc-dcd0ef560837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>9115a941-94d5-4ef1-81ed-3f4d0cdc122f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>opacity</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9ea25cb5-04f2-4cea-b76d-17ad2a547217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/nb-layout[@class=&quot;window-mode with-scroll&quot;]/div[@class=&quot;scrollable-container&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;layout-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;columns&quot;]/nb-layout-column[1]/ngx-editors[@class=&quot;ng-star-inserted&quot;]/message-detail[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row hello ng-star-inserted&quot;]/nb-icon[@class=&quot;flip-icon&quot;]/svg[@class=&quot;eva eva-close-square-outline&quot;]/g[1]/g[1]/rect[1]</value>
      <webElementGuid>fe718d48-f025-464d-8b2c-2fea1d0c2f6f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
